
    </div>
    <!-- END PAGE CONTENT -->
  </div>
  <!-- END PAGE CONTENT WRAPPER -->
</div>
<!-- END PAGE PAGE-CONTAINER -->
<div class=" container-fluid  container-fixed-lg footer">
	<div class="copyright sm-text-center">
	<p class="small-text no-margin pull-left sm-pull-reset">
	©<?=date('Y');?> All Rights Reserved. Ghost Kitchen®
	<span class="hint-text m-l-15">Ghost v01.00</span>
	</p>
	<p class="small no-margin pull-right sm-pull-reset">
	Hand-crafted <span class="hint-text">&amp; made with Love</span>
	 </p>
	<div class="clearfix"></div>
	</div>
</div>