
    <!--START QUICKVIEW -->
    <div id="quickview" class="quickview-wrapper" data-pages="quickview">
      <!-- Nav tabs -->
      <ul class="nav nav-tabs">
        <li class="" data-target="#quickview-notes" data-toggle="tab">
          <a href="#">Notes</a>
        </li>
        <li data-target="#quickview-alerts" data-toggle="tab">
          <a href="#">Alerts</a>
        </li>
        <li class="active" data-target="#quickview-chat" data-toggle="tab">
          <a href="#">Chat</a>
        </li>
      </ul>
      <a class="btn-link quickview-toggle" data-toggle-element="#quickview" data-toggle="quickview"><i class="pg-close"></i></a>
      <!-- Tab panes -->
      <div class="tab-content">
        <!-- BEGIN Notes !-->
        <div class="tab-pane no-padding active" id="quickview-alerts">
          <div class="view-port clearfix" id="alerts">
            <!-- BEGIN Alerts View !-->
              <h5 class="text-center">Filter By</h5>
            <div class="view bg-white">
              <!-- BEGIN Alert List !-->
              <div data-init-list-view="ioslist" class="list-view boreded no-top-border">
                <!-- BEGIN List Group !-->
                <div class="list-view-group-container">
                  <!-- BEGIN List Group Header!-->
                  <div class="list-view-group-header text-uppercase">
                    Departments
                  </div>
                  <!-- END List Group Header!-->
                  <ul>
                    <!-- BEGIN List Group Item!-->
                    <li class="alert-list campaign-filters">
                      <!-- BEGIN Alert Item Set Animation using data-view-animation !-->
                        <select style="width: 100%;">
                          <option value="">All</option>
                        </select>
                      <!-- END Alert Item!-->
                      <!-- BEGIN List Group Item!-->
                    </li>
                    <!-- END List Group Item!-->
                  </ul>
                </div>


                <!-- BEGIN List Group !-->
                <div class="list-view-group-container">
                  <!-- BEGIN List Group Header!-->
                  <div class="list-view-group-header text-uppercase">
                    Branches
                  </div>
                  <!-- END List Group Header!-->
                  <ul>
                    <!-- BEGIN List Group Item!-->
                    <li class="alert-list campaign-filters">
                      <!-- BEGIN Alert Item Set Animation using data-view-animation !-->
                        <select style="width: 100%;">
                          <option value="">All</option>
                        </select>
                      <!-- END Alert Item!-->
                      <!-- BEGIN List Group Item!-->
                    </li>
                    <!-- END List Group Item!-->
                  </ul>
                </div>



                <!-- BEGIN List Group !-->
                <div class="list-view-group-container">
                  <!-- BEGIN List Group Header!-->
                  <div class="list-view-group-header text-uppercase">
                    Age Group
                  </div>
                  <!-- END List Group Header!-->
                  <ul>
                    <!-- BEGIN List Group Item!-->
                    <li class="alert-list campaign-filters">
                      <!-- BEGIN Alert Item Set Animation using data-view-animation !-->
                        <select style="width: 100%;">
                          <option>18-25</option>
                          <option>25-35</option>
                          <option>35-45</option>
                          <option>45-55</option>
                          <option>55+</option>
                        </select>
                      <!-- END Alert Item!-->
                      <!-- BEGIN List Group Item!-->
                    </li>
                    <!-- END List Group Item!-->
                  </ul>
                </div>



                <!-- BEGIN List Group !-->
                <div class="list-view-group-container">
                  <!-- BEGIN List Group Header!-->
                  <div class="list-view-group-header text-uppercase">
                    Gender
                  </div>
                  <!-- END List Group Header!-->
                  <ul>
                    <!-- BEGIN List Group Item!-->
                    <li class="alert-list campaign-filters">
                      <!-- BEGIN Alert Item Set Animation using data-view-animation !-->
                        <select style="width: 100%;">
                          <option value="">All</option>
                        </select>
                      <!-- END Alert Item!-->
                      <!-- BEGIN List Group Item!-->
                    </li>
                    <!-- END List Group Item!-->
                  </ul>
                </div>



                <!-- BEGIN List Group !-->
                <div class="list-view-group-container">
                  <!-- BEGIN List Group Header!-->
                  <div class="list-view-group-header text-uppercase">
                    Years at Company
                  </div>
                  <!-- END List Group Header!-->
                  <ul>
                    <!-- BEGIN List Group Item!-->
                    <li class="alert-list campaign-filters">
                      <!-- BEGIN Alert Item Set Animation using data-view-animation !-->
                        <select style="width: 100%;">
                          <option value="">All</option>
                        </select>
                      <!-- END Alert Item!-->
                      <!-- BEGIN List Group Item!-->
                    </li>
                    <!-- END List Group Item!-->
                  </ul>
                </div>

                <!-- BEGIN List Group !-->
                <div class="list-view-group-container">
                  <!-- BEGIN List Group Header!-->
                  <div class="list-view-group-header text-uppercase">
                    Role type
                  </div>
                  <!-- END List Group Header!-->
                  <ul>
                    <!-- BEGIN List Group Item!-->
                    <li class="alert-list campaign-filters">
                      <!-- BEGIN Alert Item Set Animation using data-view-animation !-->
                        <select style="width: 100%;">
                          <option value="">All</option>
                        </select>
                      <!-- END Alert Item!-->
                      <!-- BEGIN List Group Item!-->
                    </li>
                    <!-- END List Group Item!-->
                  </ul>
                </div>

                <!-- END List Group !-->
              </div>
              <!-- END Alert List !-->
            </div>
            <!-- EEND Alerts View !-->
          </div>

        </div>
      </div>
    </div>
    <!-- END QUICKVIEW-->