<nav class="page-sidebar" data-pages="sidebar">
  <!-- BEGIN SIDEBAR MENU TOP TRAY CONTENT-->
  <!-- END SIDEBAR MENU TOP TRAY CONTENT-->
  <!-- BEGIN SIDEBAR MENU HEADER-->
  <div class="sidebar-header p-r-0 p-l-15">
    <img src="http://www.uniques.ca/images/logo-officio.jpg" alt="logo" class="brand" data-src="<?=_SITEROOT_;?>assets/public/img/logo-new-white.png" data-src-retina="<?=_SITEROOT_;?>assets/public/img/logo-new-white.png" width="100">
    <div class="sidebar-header-controls">
      <button type="button" class="btn btn-link d-lg-inline-block d-xlg-inline-block d-md-inline-block d-sm-none d-none" data-toggle-pin="sidebar"><i class="fa fs-12"></i>
      </button>
    </div>
  </div>
  <!-- END SIDEBAR MENU HEADER-->
  <!-- START SIDEBAR MENU -->
  <div class="sidebar-menu">
    <!-- BEGIN SIDEBAR MENU ITEMS-->
    <ul class="menu-items">
      <li class="<?=($equrl[1] == '' ? 'active' : '');?>">
        <a href="/forecast/calendar">Calendar</a>
        <span class="icon-thumbnail fa fa-calendar" style="font-family: fontawesome;"></span>
      </li>
      <li class="<?=($equrl[1] == 'mailer' ? 'active' : '');?>">
        <a href="/forecast/mail">Mailer</a>
        <span class="icon-thumbnail fa fa-envelope" style="font-family: fontawesome;"></span>
      </li>
      <li class="<?=($equrl[1] == 'vimeo' ? 'active' : '');?>">
        <a href="/forecast/vimeo">Vimeo</a>
        <span class="icon-thumbnail fa fa-video-camera  " style="font-family: fontawesome;"></span>
      </li>
      <li class="<?=($equrl[1] == 'vimeo' ? 'active' : '');?>">
        <a href="/forecast/docx">DocX Converter</a>
        <span class="icon-thumbnail fa fa-file" style="font-family: fontawesome;"></span>
      </li>
    </ul>
    <div class="clearfix"></div>
  </div>
  <!-- END SIDEBAR MENU -->
</nav>