<div class="container">
  <!-- START Login Right Container-->
  <div class="col-md-6 login-container bg-white">
    <div class="p-l-50 m-l-20 p-r-50 m-r-20 p-t-50 m-t-30 sm-p-l-15 sm-p-r-15 sm-p-t-40">
      <img src="http://www.uniques.ca/images/logo-officio.jpg" width="200px">
      <p class="p-t-10">Sign into your scouty account</p>
      <!-- START Login Form -->
      <form id="form-login" class="p-t-15" role="form">
        <!-- START Form Control-->
        <div class="form-group form-group-default">
          <label>Login</label>
          <div class="controls">
            <input type="text" name="username" placeholder="User Name" class="form-control" autocomplete="off" required>
          </div>
        </div>
        <!-- END Form Control-->
        <!-- START Form Control-->
        <div class="form-group form-group-default">
          <label>Password</label>
          <div class="controls">
            <input type="password" class="form-control" name="password" placeholder="Credentials" autocomplete="off" required>
          </div>
        </div>
        <!-- START Form Control-->
        <div class="row">
          <div class="col-md-6 no-padding sm-p-l-10">
            <div class="checkbox ">
              <input type="checkbox" value="1" id="checkbox1">
              <label for="checkbox1">Keep Me Signed in</label>
            </div>
          </div>
          <!-- <div class="col-md-6 d-flex align-items-center justify-content-end">
            <a href="#" class="text-info small">Help? Contact Support</a>
          </div> -->
        </div>
        <!-- END Form Control-->
        <button class="btn btn-primary btn-cons m-t-10" type="submit">Sign in</button>
      </form>
      <!--END Login Form-->
      <div class="pull-bottom sm-pull-bottom">
        <div class="m-b-30 p-r-80 sm-m-t-20 sm-p-r-15 sm-p-b-20 clearfix">
          <div class="col-sm-3 col-md-2 no-padding">
            <img alt="" class="m-t-5" data-src="/assets/public/img/logo-lg-white.png" data-src-retina="/assets/public/img/logo-lg-white.png" height="60" src="/assets/public/img/logo-lg-white.png" width="60">
          </div>
          <!-- <div class="col-sm-9 no-padding m-t-10">
            <p>
              <small>
				        Create a pages account. If you have a facebook account, log into it for this process. Sign in with <a href="#" class="text-info">Facebook</a> or <a href="#" class="text-info">Google</a>
              </small>
            </p>
          </div> -->
        </div>
      </div>
    </div>
  </div>
  <!-- END Login Right Container-->
</div>