<nav class="secondary-sidebar" style="margin-top:-60px;">
	<ul class="main-menu">
		<li>
			<a data-document="onlyofficesample.docx">
                <span class="title">onlyofficesample.docx</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_1MB.docx">
                <span class="title">file-sample_1MB.docx</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_100kB.docx">
                <span class="title">file-sample_100kB.docx</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_500kB.docx">
                <span class="title">file-sample_500kB.docx</span> 
            </a>
		</li>
	</ul>
</nav>
<div class="inner-content full-height padding-20">
    <a class="btn btn-primary hidden">Open Document</a>
    <div id="content">
        <h4 class="text-center">Please pick a document on the left</h4>
    </div>
</div>