<nav class="secondary-sidebar" style="margin-top:-60px;">
	<ul class="main-menu">
		<li>
			<a data-document="file-sample_1MB.doc">
                <span class="title">Doc 1</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_1MB.docx">
                <span class="title">Doc 2</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_100kB.doc">
                <span class="title">Doc 3</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_100kB.docx">
                <span class="title">Doc 4</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_500kB.doc">
                <span class="title">Doc 5</span> 
            </a>
		</li>
		<li>
			<a data-document="file-sample_500kB.docx">
                <span class="title">Doc 6</span> 
            </a>
		</li>
	</ul>
</nav>
<div class="inner-content full-height padding-20">
    <h4 class="text-center">Please pick a document on the left</h4>
</div>