<nav class="navbar navbar-default bg-master-lighter full-width p-t-0 p-b-0" role="navigation">
	<div class="container-fluid full-width">
		<div class="navbar-header text-center">
			<button class="navbar-toggle collapsed btn btn-link no-padding" data-target="#sub-nav" data-toggle="collapse" type="button"><i class="pg pg-more v-align-middle"></i></button>
		</div>
		<div class="collapse navbar-collapse" id="sub-nav">
			<div class="row">
				<div class="col-sm-6">
				</div>
				<div class="col-sm-6">
					<ul class="navbar-nav d-flex flex-row justify-content-sm-end">
						<li class="nav-item text-center">
							<a data-original-title="Print" data-placement="bottom" data-toggle="tooltip" href="#" onclick="window.print()" title=""><i class="fa fa-print"></i></a>
						</li>
						<li class="nav-item">
							<a class="p-r-10" href="#" onclick="$.Pages.setFullScreen(document.querySelector('html'));"><i class="fa fa-expand"></i></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>
<div class="container-fluid container-fixed-lg">
	<div class="card card-default m-t-20">
		<div class="card-body">
			<div class="invoice padding-50 sm-padding-10">
				<div>
					<div class="pull-left">
						<img alt="" class="invoice-logo" data-src="/assets/public/img/logo-new-black.png" data-src-retina="/assets/public/img/logo-new-black.png" src="/assets/public/img/logo-new-black.png" width="100">
						<address class="m-t-10">
							<strong><?=$_SESSION['scouty_company_name'];?></strong><br>
							<?php  //$this->companyAddress; ?>
							<?=$_SESSION['scouty_company_phone'];?><br>
						</address>
					</div>
					<div class="pull-right sm-m-t-20">
						<h2 class="font-montserrat all-caps hint-text">Invoice</h2>
					</div>
					<div class="clearfix"></div>
				</div><br>
				<br>
				<div class="col-12">
					<div class="paid-stamp <?php if(!in_array($this->invoiceData['paid'], ['0'])): ?>hidden<?php endif;?>"></div>
					<div class="row">
						<div class="col-lg-8 col-sm-height sm-no-padding">
							<p class="small no-margin">Invoice to:</p>
							<strong>
								<?=$this->invoiceData['client']['name'];?>
							</strong>
							<address>
								<?=$this->invoiceData['client']['address'];?><br/>
								<?=$this->invoiceData['client']['phone'];?>
							</address>
						</div>
						<div class="col-lg-4 sm-no-padding sm-p-b-20 d-flex align-items-end justify-content-between">
							<div>
								<div class="font-montserrat bold all-caps">
									Event Date :
								</div>
								<div class="font-montserrat bold all-caps">
									Invoice No :
								</div>
								<div class="font-montserrat bold all-caps">
									Invoice date :
								</div>
								<div class="clearfix"></div>
							</div>
							<div class="text-right">
								<div class="">
									<?=$this->invoiceData['eventDate'];?>
								</div>
								<div class="">
									<?=$this->invoiceData['invoiceNum'];?>
								</div>
								<div class="">
									<?=$this->invoiceData['today'];?>
								</div>
								<div class="clearfix"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="table-responsive table-invoice">
					<table class="table m-t-50">
						<thead>
							<tr>
								<th class="">Product</th>
								<th class="text-right p-r-0">Rate</th>
								<th class="text-right p-r-0">Amount</th>
								<th class="text-right p-r-0">Total</th>
							</tr>
						</thead>
						<tbody>
					<?php foreach($this->invoiceData['data'] as $key => $val): ?>
							<tr>
								<td class="">

									<?php foreach($val as $key2 => $val2): ?>
										<h6 class="m-t-0 m-b-0 semi-bold text-black"><?=$key2;?>&nbsp;<small></small></h6>

										<?php foreach($val2 as $key3 => $val3): ?>
											<p class="m-b-0 hint-text">&nbsp;&nbsp;<?=$key3;?></p>

										<?php endforeach;?>
									<?php endforeach;?>

								</td>
								<td class="text-right p-r-0">
									<?php foreach($val as $key2 => $val2): ?>
										<h6 class="m-t-0 m-b-0 semi-bold text-black">&nbsp;</h6>
										<?php foreach($val2 as $key3 => $val3): ?>
											
											<p class="m-b-0 hint-text">$<?=number_format($val3[0]['price'],2);?></p>

										<?php endforeach;?>
									<?php endforeach;?>

								</td>
								<td class="text-right p-r-0">
									<?php foreach($val as $key2 => $val2): ?>
										<h6 class="m-t-0 m-b-0 semi-bold text-black">&nbsp;</h6>
										<?php foreach($val2 as $key3 => $val3): ?>
											
											<p class="m-b-0 hint-text"><?=$val3[0]['total'];?></p>

										<?php endforeach;?>
									<?php endforeach;?>

								</td>
								<td class="text-right p-r-0">
									<?php foreach($val as $key2 => $val2): ?>
										<h6 class="m-t-0 m-b-0 semi-bold text-black">&nbsp;</h6>
										<?php foreach($val2 as $key3 => $val3): ?>
											
											<p class="m-b-0 hint-text">$<?=number_format($val3[0]['price']*$val3[0]['total'],2);?></p>

										<?php endforeach;?>
									<?php endforeach;?>

								</td>
							</tr>
						
					<?php endforeach;?>
						</tbody>
					</table>
				</div><br>
				<br>
				<br>
				<br>
				<br>
				<div>
					<!-- <img alt="" class="invoice-signature" data-src="assets/img/invoice/signature.png" data-src-retina="assets/img/invoice/signature2x.png" height="58" src="assets/img/invoice/signature2x.png" width="150">
					<p>Designer’s Identity</p> -->
				</div><br>
				<br>
				<div class="p-l-15 p-r-15">
					<div class="row b-a b-grey">
						<div class="col-md-2 p-l-15 sm-p-t-15 clearfix sm-p-b-15 d-flex flex-column justify-content-center">
							<!-- <h5 class="font-montserrat all-caps small no-margin hint-text bold">Advance</h5>
							<input type="number" value="0" id="advance"> -->
						</div>
						<div class="col-md-5 clearfix sm-p-b-15 d-flex flex-column justify-content-center">
							<!-- <h5 class="font-montserrat all-caps small no-margin hint-text bold">Discount (10%)</h5>
							<h4 class="no-margin">$645.00</h4> -->
						</div>
						<div class="col-md-5 text-right bg-master-darker col-sm-height padding-15 d-flex flex-column justify-content-center align-items-end">
							<h5 class="font-montserrat all-caps small no-margin hint-text text-white bold">Grand Total</h5>
							<h1 class="no-margin text-white" id="total" data-total="<?=$this->invoiceData['total'];?>">$<?=number_format($this->invoiceData['total'],2);?></h1>
						</div>
					</div>
				</div>
				<hr>
				<p class="small hint-text">Services will be invoiced in accordance with the Service Description. You must pay all undisputed invoices in full within 30 days of the invoice date, unless otherwise specified under the Special Terms and Conditions. All payments must reference the invoice number. Unless otherwise specified, all invoices shall be paid in the currency of the invoice</p>
				<p class="small hint-text">Insight retains the right to decline to extend credit and to require that the applicable purchase price be paid prior to performance of Services based on changes in insight's credit policies or your financial condition and/or payment record. Insight reserves the right to charge interest of 1.5% per month or the maximum allowable by applicable law, whichever is less, for any undisputed past due invoices. You are responsible for all costs of collection, including reasonable attorneys' fees, for any payment default on undisputed invoices. In addition, Insight may terminate all further work if payment is not received in a timely manner.</p><br>
				<hr>
				<div>
					<!-- <img alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" height="22" src="assets/img/logo.png" width="78">  -->
					<span class="m-l-70 text-black sm-pull-right"><?=$_SESSION['scouty_company_phone'];?></span> <span class="m-l-40 text-black sm-pull-right"><?=$_SESSION['scouty_company_email'];?></span>
				</div>
			</div>
		</div>
	</div>
</div>