<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href="/forecast/">Forecast</a></li>
    <li class="breadcrumb-item active">Calendar</li>
  </ol>
</div>
<div class="select2-filter-container">
  <div class="col-md-5 padding-20">
    <select data-init-plugin="select2" id="channelFilterDD">
        <option value="">All clients</option>
      <?php foreach($this->channels as $channel): ?>
        <option value="<?=$channel['id'];?>"><?=$channel['name'];?></option>
      <?php endforeach;?>
    </select>
  </div>
  <div id="calendar" class="padding-20 full-height bg-white"></div>
  <div class="cal-overlay"></div>
</div>
<!-- END CALENDAR -->
<!-- START EVENT MANAGER -->
<!-- START Calendar Events Form -->
<div class="quickview-wrapper calendar-event" id="calendar-event" data-event-type="">
  <div class="view-port clearfix" id="eventFormController">
    <div class="loading"></div>
    <div class="view bg-white">
      <div class="scrollable">
        <div class="p-l-15 p-r-30 p-t-20">
          <a class="pg-close text-master link pull-right" data-close-it="quickview" href="#">
            <i class="flaticon flaticon-multiply"></i>
          </a>
          <h4 class="m-b-5 m-t-0" id="event-date"></h4>
          <div class="m-b-0">
            <i class="fa fa-clock-o"></i>
            <span id="lblfromTime"></span> to
            <span id="lbltoTime"></span>
          </div>
          <div class="m-b-0">
            <i class="fa fa-user"></i>
            <span id="mainContact"></span>
          </div>
          <div class="m-b-5">
            <i class="fa fa-phone"></i>
            <span id="phone"></span>
          </div>
        </div>
        <div class="p-t-15">
          <input id="grocery-list" name="grocery-list" type="hidden">
          <div class="form-group-attached">
            <div class="form-group form-group-default ">
              <label>Event Type 
                <a class="event-type-question">
                  <i class="fa fa-question-circle"></i>
                </a>
              </label>
              <div class="m-t-10 m-b-0 radio radio-primary radio-circle event-types">
                <input type="radio" class="user-status" id="eventCheck" name="eventType" value="public"/>
                <label for="eventCheck" style="margin-left: 0;">Public</label>
                <input type="radio" class="user-status" id="eventCheck2" name="eventType" value="private"/>
                <label for="eventCheck2">Private</label>
              </div>
            </div>
            <div class="form-group form-group-default ">
              <label>Channel</label>
              <select data-init-plugin="select2" style="width:100%;" id="channelDD" disabled>
                <option value="">Select Channel...</option>
                <?php foreach($this->channels as $channel): ?>
                  <option value="<?=$channel['id'];?>"><?=$channel['name'];?></option>
                <?php endforeach;?>
              </select>
            </div>
            <div class="row clearfix">
              <div class="col-sm-6">
                <div class="form-group form-group-default">
                  <label>Start Time</label>
                  <select class="select-2" style="width:100%;" id="startTimeDD">
                    <option>00:00</option>
                    <option>00:30</option>
                    <option>01:00</option>
                    <option>01:30</option>
                    <option>02:00</option>
                    <option>02:30</option>
                    <option>03:00</option>
                    <option>03:30</option>
                    <option>04:00</option>
                    <option>04:30</option>
                    <option>05:00</option>
                    <option>05:30</option>
                    <option>06:00</option>
                    <option>06:30</option>
                    <option>07:00</option>
                    <option>07:30</option>
                    <option>08:00</option>
                    <option>08:30</option>
                    <option>09:00</option>
                    <option>09:30</option>
                    <option>10:00</option>
                    <option>10:30</option>
                    <option>11:00</option>
                    <option>11:30</option>
                    <option>12:00</option>
                    <option>12:30</option>
                    <option>13:00</option>
                    <option>13:30</option>
                    <option>14:00</option>
                    <option>14:30</option>
                    <option>15:00</option>
                    <option>15:30</option>
                    <option>16:00</option>
                    <option>16:30</option>
                    <option>17:00</option>
                    <option>17:30</option>
                    <option>18:00</option>
                    <option>18:30</option>
                    <option>19:00</option>
                    <option>19:30</option>
                    <option>20:00</option>
                    <option>20:30</option>
                    <option>21:00</option>
                    <option>21:30</option>
                    <option>22:00</option>
                    <option>22:30</option>
                    <option>23:00</option>
                    <option>23:30</option>
                  </select>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group form-group-default">
                  <label>End Time</label>
                  <select class="select-2" style="width:100%;" id="endTimeDD">
                    <option>00:00</option>
                    <option>00:30</option>
                    <option>01:00</option>
                    <option>01:30</option>
                    <option>02:00</option>
                    <option>02:30</option>
                    <option>03:00</option>
                    <option>03:30</option>
                    <option>04:00</option>
                    <option>04:30</option>
                    <option>05:00</option>
                    <option>05:30</option>
                    <option>06:00</option>
                    <option>06:30</option>
                    <option>07:00</option>
                    <option>07:30</option>
                    <option>08:00</option>
                    <option>08:30</option>
                    <option>09:00</option>
                    <option>09:30</option>
                    <option>10:00</option>
                    <option>10:30</option>
                    <option>11:00</option>
                    <option>11:30</option>
                    <option>12:00</option>
                    <option>12:30</option>
                    <option>13:00</option>
                    <option>13:30</option>
                    <option>14:00</option>
                    <option>14:30</option>
                    <option>15:00</option>
                    <option>15:30</option>
                    <option>16:00</option>
                    <option>16:30</option>
                    <option>17:00</option>
                    <option>17:30</option>
                    <option>18:00</option>
                    <option>18:30</option>
                    <option>19:00</option>
                    <option>19:30</option>
                    <option>20:00</option>
                    <option>20:30</option>
                    <option>21:00</option>
                    <option>21:30</option>
                    <option>22:00</option>
                    <option>22:30</option>
                    <option>23:00</option>
                    <option>23:30</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="row clearfix">
              <div class="form-group form-group-default">
                <label>Order slist</label>
                <div id="order-list" class="p-t-5 p-b-5">
                  list empty
                </div>
              </div>
              <div class="form-group form-group-default">
                <label>Recipe</label>
                <div class="col-sm-12 p-l-0 p-r-0">
                  <select class="select-2" data-placeholder="Choose..." style="width:100%;" id="input-recipe">
                    <?php foreach($this->subRecipes as $key => $sub): ?>
                      <!-- <option value="">Choose..</option> -->
                      <optgroup label="<?=$key;?>"><?=$key;?></optgroup>
                      <?php foreach($sub as $key2 => $sub2): ?>
                        <option value="<?=$sub2['id'];?>" 
                          data-recipe-id="<?=$sub2['recipe_id'];?>" 
                          data-recipe-name="<?=$key;?>" 
                          data-recipe-sub-price="<?=$sub2['price'];?>" 
                          data-recipe-sub-name="<?=$sub2['containerSize'] . ' ' . $sub2['container'];?>">
                          <small style="font-size: 10px;">
                            <?=$key . ' ' . $sub2['containerSize'] . ' ' . $sub2['container'];?>
                          </small>
                        </option>
                      <?php endforeach;?>
                      
                    <?php endforeach; ?>
                  </select>
                </div>
                <div class="col-sm-12 p-l-0 p-r-0">
                  <label>Amount</label>
                  <input type="number" id="input-recipe-amt" class="form-control p-t-5 p-b-5">
                </div>
                <a class="m-t-15 btn btn-primary text-white btn-block add-offer">Add To Order</a>
              </div>
            </div>
            <div class="row clearfix">
              <div class="form-group form-group-default">
                <label>Note</label>
                <textarea class="form-control" rows="40" id="txtEventDesc"></textarea>
              </div>
            </div>
          </div>
        </div>
        <div class="p-l-30 p-r-30 p-t-30 p-b-50">
          <button id="eventSave" class="btn btn-primary btn-cons">Save Event</button>
          <button id="eventDelete" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
        </div>
      </div>
    </div>

  </div>
</div>
<!-- END Calendar Events Form -->
<!-- START EVENT MANAGER -->