<script src="https://code.jquery.com/jquery-3.1.0.js"></script> <iframe id="iframe" src="https://player.vimeo.com/video/354303820" width="100%" height="400px" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<script src="https://player.vimeo.com/api/player.js"></script>
<br/>
<br/>
 <h3 class="text-center bold">The current time is <br/><span id="currentTime" class="light">0</span><br/> seconds</h3>
 <script>
    var id = $(this).attr("id");
    var iframe = document.getElementById('iframe');
    var vPlayer = new Vimeo.Player(iframe);

setInterval(function ()
{
    var currtym = vPlayer.getCurrentTime();
    var currentTime = 0;
    vPlayer.getCurrentTime().then(function(currentTime) {    
      $('#currentTime').html(currentTime);
    });
}, 2);
 </script>